version: 2.1
jobs:
  compile:
    docker:
      - image: mhmmdfas/mydockerimage:latest
    steps:
      - run: git clone -j32 https://github.com/Mhmmdfas/android_kernel_xiaomi_msm8917-2 -b oreo-pie --depth=1 .
      - run: wget https://raw.githubusercontent.com/Mhmmdfas/android_kernel_xiaomi_msm8917-2/oreo-pie/test
      - run: chmod +x test
      - run: bash test
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
