version: 2
jobs:
  build:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - checkout
      - run: wget https://github.com/timangpopi1/scripts/raw/master/kernel.sh
      - run: kernel.sh
